export const ADD_DUMMY = 'ADD_DUMMY';
export const COUNT_DUMDUM = 'COUNT_DUMDUM';
export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_REVIEW_METADATA = 'GET_REVIEW_METADATA';
export const GET_RELATED_PRODUCTS = "GET_RELATED_PRODUCTS";
export const GET_RELATED_IMAGES = "GET_RELATED_IMAGES";