export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_REVIEW_METADATA = 'GET_REVIEW_METADATA';
export const GET_RELATED_PRODUCTS = "GET_RELATED_PRODUCTS";
export const GET_RELATED_IMAGES = "GET_RELATED_IMAGES";
export const GET_RELATED_REVIEWS = "GET_RELATED_REVIEWS";
export const GET_QUESTIONS = "GET_QUESTIONS";